### ISSUE TITLE
麻烦作者进来看一下，快手没法使用

### ISSUE THREAD

**Issue by sddz6269** [BurpSuite/UPlus-Shadowrocket#10]
如题，然后就是如何在配置里设置取消IPHONE任务栏VPN图标的显示，在用别的配置的时候发现VPN图标可以不显示，习惯了…… 表示不想让他显示 不知道可不可以 谢谢！

**Comment by burpsuite** [comment]
1.快手实测可以使用,本次测试版本号为:4.93.0
2.配置文件无法取消图标的,其他的规则我也用过,都是无法取消的!
3.如有其他问题可以继续追问,如果没有请点右下角"Close issue"谢谢!

**Comment by sddz6269** [comment]
好的 谢谢！

**Comment by sddz6269** [comment]
![wechatimg22](https://cloud.githubusercontent.com/assets/21240255/18026261/6a77f01a-6c73-11e6-8cc0-9d88dd59c062.jpeg)
![wechatimg23](https://cloud.githubusercontent.com/assets/21240255/18026262/6df0df7c-6c73-11e6-9999-ec74e007257d.jpeg)
奇怪了……我快手的确不行……………… 难道是个例么……………… 版本号一样的 我重装试试看

**Comment by burpsuite** [comment]
好的,我再看一下!稍等!

**Comment by sddz6269** [comment]
谢谢😜 用你surge的规则看快手就没问题…… 但是觉得shadowrocket更省电… 麻烦您了

**Comment by burpsuite** [comment]
抱歉,之前弄错了,我用Potatso试的,这次是用Shadowrocket试的,已确认有此问题,不过无法解决,尝试了IP-CIDR+Bypass-tun+Skip-Proxy都是无法解决,日志中显示180.186.38.200/32和101.251.217.210/32均被REJECT,我实测别的规则也是这样.唯一的方法请联系Shadowrocket的开发者!这个错误和Potatso不能听虾米音乐一样!不能听音乐这个我也汇报过,不过从刚上架到现在一直无法解决!我联系好像都不回复我,所以还得你自己联系一下,呃(-｡-;)

**Comment by burpsuite** [comment]
简单来说的话就是"属于程序问题"

**Comment by sddz6269** [comment]
哦哦明白了…… 谢谢您了 辛苦了 我先用着SURGE吧~ 谢谢您的付出

**Comment by burpsuite** [comment]
已经找到问题了,把IP-CIDR REJECT段全删除就行了!我再重新排查一下!
虽然是删除就可以了,不过我还是觉得Shadowrocket也有问题
