### ISSUE TITLE
手机QQ好友头像及从手机QQ进入QQ空间好友发布动态中包含的图片加载不出来

### ISSUE THREAD

**Issue by LennyDu** [BurpSuite/UPlus-Shadowrocket#11]
手机QQ好友头像及从手机QQ进入QQ空间好友发布动态中包含的图片加载不出来

**Comment by burpsuite** [comment]
发来完全版的请求截图

**Comment by burpsuite** [comment]
关闭所有后台，打开代理，开启日志功能，打开QQ，然后点击你说的那些，然后再回到代理，然后截图

**Comment by LennyDu** [comment]
稍等

**Comment by burpsuite** [comment]
嗯

**Comment by LennyDu** [comment]
<img width="704" alt="2016-09-04 16 40 40" src="https://cloud.githubusercontent.com/assets/9624796/18229942/6abcad26-72be-11e6-88d5-3fce1fb29e26.png">
这个是QQ好友头像加载的时候发的请求

**Comment by burpsuite** [comment]
好的,稍等,稍后我复现一下!

**Comment by LennyDu** [comment]
<img width="477" alt="2016-09-04 16 54 28" src="https://cloud.githubusercontent.com/assets/9624796/18229975/535f0712-72c0-11e6-9a2b-9948ab96b1d2.png">
图片中第一个GET是手机QQ进入QQ空间好友发布动态中包含的图片的GET请求，第二个GET好像是空间中某个游戏广告的截图，第三个请求不知道是什么东西了。这个测试不能用手机本地的图片，手机本地的图片手机QQ好像可以直接读本地，没有发请求

**Comment by burpsuite** [comment]
这个我知道,gdt=广点通,我看到了,挺多请求都被REJECT了,

**Comment by burpsuite** [comment]
我并没有设置这些IP-CIDR被REJECT,我一会找一下问题

**Comment by LennyDu** [comment]
好的，谢谢了，希望早点更新哈

**Comment by LennyDu** [comment]
今天又没有这个问题了，今天获取头像发送的get请求是向这个IP段发送的163.177.68.200:80

**Comment by burpsuite** [comment]
好的,知道!我会尽快修复!由于最近正在编写更新AdvertFilter4.0版本,所以修复可能有点晚!最晚2天以内修复好!

**Comment by burpsuite** [comment]
已经找到问题了,把IP-CIDR REJECT段全删除就行了!

**Comment by LennyDu** [comment]
那帮忙更新一下文件吧，习惯了从你这里直接下载配置，谢谢啦

**Comment by burpsuite** [comment]
好了,已经更新!

**Comment by LennyDu** [comment]
非常感谢
