### ISSUE TITLE
[知乎]:“发生了SSL错误，无法建立与该服务器的安全连接。”或者直接加载不出来内容||[网易新闻]刷新失败，提示“网络不给力”

### ISSUE THREAD

**Issue by LennyDu** [BurpSuite/UPlus-Shadowrocket#12]
目前我只是从“首页”随便点一个热门回答，进去就会发生这种情况，知乎内其他的还没有测试，希望作者帮忙解决一下这个问题。不用VPN直接连接的时候是正常访问。
[网易新闻]刷新新闻失败，提示“网络不给力”

**Comment by burpsuite** [comment]
可能是网络原因,你重启下设备尝试一下!网易新闻版本:15.1,知乎版本:3.23.0,Shadowrocket版本:2.0.10(128)
![img_0110](https://cloud.githubusercontent.com/assets/14309190/18464980/c6f29f92-79c6-11e6-942e-af434a035add.PNG)
![img_0106](https://cloud.githubusercontent.com/assets/14309190/18464982/c722abd8-79c6-11e6-8e91-c5d4ba40f228.PNG)
![img_0107](https://cloud.githubusercontent.com/assets/14309190/18464983/c7568a8e-79c6-11e6-96bb-9403c229a225.PNG)
![img_0109](https://cloud.githubusercontent.com/assets/14309190/18464984/c766b5a8-79c6-11e6-991d-fc05f5a41c5a.PNG)

**Comment by LennyDu** [comment]
找到原因了，4G网络不稳定，我换成3G网络就好了，不好意思哈
