### ISSUE TITLE
配置无法加载QQ图片和QQ空间图片

### ISSUE THREAD

**Issue by Srar** [BurpSuite/UPlus-Shadowrocket#13]
如题.市面上别的配置也有类似问题 坐标:上海

感谢查看我的issues

**Comment by Srar** [comment]
补充下 用腾讯CDN的貌似都有这个问题，比如格瓦拉会提示网络错误

**Comment by burpsuite** [comment]
是的,Shadowrocket会出现各种怪问题,你说的这个应该是IP-CIDR被Shadowrocket REJECT导致的,通过规则的SKIP-Proxy等都无法解决,这个我认为是Shadowrocket开发者的问题!我暂时取消掉了IP-CIDR项,你可以重新导入一下,然后再试试!另外此问题你也可以反馈给Shadowrocket开发者!

**Comment by Srar** [comment]
感谢回复 那我去找作者提issue 麻烦吧这个issue关闭吧 谢谢！
