### ISSUE TITLE
最新版本iOS10无VPN连接图标

### ISSUE THREAD

**Issue by lifeva** [BurpSuite/UPlus-Shadowrocket#14]
顶部状态栏没有连接VPN的小图标了

**Comment by burpsuite** [comment]
这个属于正常问题!稍后我附上解释

**Comment by burpsuite** [comment]
URL:https://trello.com/c/dLhyuDeh
在 iOS 10 的系统下，是否显示 VPN 的标示，是根据 VPN 声明的路由表决定的。

如果 VPN 的路由表中，排除掉了 0.0.0.0/31，那么即使 VPN 已连接，也不会显示 VPN 标示。反之则显示。

所以，如果你想在 iOS 10 下隐藏 VPN 标示，请在 bypass-tun 选项中加入 0.0.0.0/31。如果不想隐藏，请去掉 0.0.0.0/x

目前看来是否排除没有任何实质的作用和影响，关于 0.0.0.0/8 的 RFC 定义如下
0.0.0.0/8 - Addresses in this block refer to source hosts on "this"
network. Address 0.0.0.0/32 may be used as a source address for this
host on this network; other addresses within 0.0.0.0/8 may be used to
refer to specified hosts on this network [RFC1700, page 4].

**Comment by lifeva** [comment]
明白了，那是否保留那一条设置，对自动选择流量的路径是否有实质性影响呢？

**Comment by burpsuite** [comment]
行,需要我就去掉,稍后更新!对自动选择流量没有影响,只是个图标而已.

**Comment by lifeva** [comment]
还有就是ins取不到位置信息了，你看下是不是这样

**Comment by burpsuite** [comment]
按理说不应该,我一会看看.

**Comment by burpsuite** [comment]
抱歉，回复晚了，已修正！(VPN图标)

**Comment by LennyDu** [comment]
conf文件好像没更新吧，显示的最后一次更新时间还是7days ago

**Comment by burpsuite** [comment]
通过URL导入

**Comment by LennyDu** [comment]
https://github.com/BurpSuite/UPlus-Shadowrocket/blob/master/Shadowrocket.Conf 这个地址吗？这个地址导入好像还是没有显示图标，能麻烦把地址贴出来吗？新手不懂，见谅

**Comment by burpsuite** [comment]
https://Config.daoapp.io/Proxy/Shadowrocket.php

**Comment by burpsuite** [comment]
或 http://uplus7.win/Proxy/Shadowrocket.php

**Comment by LennyDu** [comment]
非常感谢

**Comment by burpsuite** [comment]
没事哈

**Comment by Mark-AQ** [comment]
> URL：[https](https://trello.com/c/dLhyuDeh)：
> //trello.com/c/dLhyuDeh在iOS 10的系统下，是否显示VPN的标示，是根据VPN声明的路由表决定的。
> 
> 如果VPN的路由表中，排除掉了0.0.0.0/31，那么即使VPN已连接，也不会显示VPN标示。反之则显示。
> 
> 所以，如果你想在iOS 10下隐藏VPN标示，请在bypass-tun选项中加入0.0.0.0/31。如果不想隐藏，请去掉0.0.0.0/x
> 
> 目前看来是否排除没有任何实质的作用和影响，关于0.0.0.0/8的RFC定义如下
> 0.0.0.0/8 - 此块中的地址是指“此” 
> 网络上的源主机。地址0.0.0.0/32可以用作
> 该网络上该主机的源地址; 0.0.0.0/8内的其他地址可用于
> 指代此网络上的指定主机[RFC1700，第4页]。

兄弟这个怎么搞回来呢不想隐藏
