### ISSUE TITLE
Google allo不能触发自动vpn连接

### ISSUE THREAD

**Issue by lifeva** [BurpSuite/UPlus-Shadowrocket#15]
如题，能否增加相应规则，谢谢！

**Comment by burpsuite** [comment]
行,我看一下

**Comment by BurpSuite** [comment]
![img_0074](https://cloud.githubusercontent.com/assets/14309190/18799070/523b790e-8208-11e6-8a20-723b1dcef912.PNG)
没有问题啊

**Comment by burpsuite** [comment]
已测试,Google Allo 确实无法使用,包括登陆,已测试Shadowrocket自带规则,发现依然无法登陆,不属于规则问题,测试Surge没有遇到此问题,我认为应该是程序问题,请联系Shadowrocket开发者解决!谢谢!
![img_0076](https://cloud.githubusercontent.com/assets/14309190/18799362/c622cfce-8209-11e6-94fd-95c4c5f97261.PNG)

**Comment by lifeva** [comment]
收到，谢谢

**Comment by burpsuite** [comment]
没事
