### ISSUE TITLE
到底该不该 FINAL 走 Proxy ？

### ISSUE THREAD

**Issue by maxming2333** [BurpSuite/UPlus-Shadowrocket#17]
既然列出了list，那么按道理基本上满足了需求了

匹配到了 `FINAL` 应该让他走 `DIRECT`

这里就有一个典型的案例 ：

FINAL 走了 Proxy 后，打开微信公众号，请求的图片就走了 proxy，

有时候loading图片会转很久，因为走了 proxy 导致图片一直没下载下来

甚至有时候根本下载不下来，图片就一直变成了 loading 图片了

![image](https://cloud.githubusercontent.com/assets/8816730/19261688/76ce6f18-8fc5-11e6-8c53-a2305b2eec85.png)

**Comment by burpsuite** [comment]
这个是Shadowrocket自身的问题，你换成Surge或者其他绝对没有这个问题。

**Comment by burpsuite** [comment]
GEOIP就可以判断基本上所有的国内地址，再加上FINAL就有点多余了，而且有一些应用的地址并不在列表里

**Comment by burpsuite** [comment]
这样会导致那些应用如果被Wall的话，FINAL DIRECT会出现网络错误

**Comment by burpsuite** [comment]
这个问题的话，我加一个规则，不过不一定能解决，Shadowrocket对于腾讯IP的有误拦截，最好的办法就是换掉Shadowrocket

**Comment by maxming2333** [comment]
目前来说我使用 `FINAL, DIRECT` 非常爽~

**Comment by maxming2333** [comment]
推荐使用 Surge ？
还有其他推荐么

**Comment by burpsuite** [comment]
除了Shadowrocket

**Comment by burpsuite** [comment]
其他没有这个问题

**Comment by maxming2333** [comment]
推荐一个呗，`Potatso` 咋样 ？

**Comment by burpsuite** [comment]
不仅微信，还包括QQ，你用Shadowrocket和Potatso或其他，代理后清除QQ缓存，然后再打开QQ，你会发现Shadowrocket载入非常慢，甚至无法载入，Potatso或者其他就没有这个问题。

**Comment by burpsuite** [comment]
Potatso Today有问题，有时候在Today无法连接，Potatso无法使用虾米音乐，哦对，不支持 URLRewrite，其他的还好

**Comment by maxming2333** [comment]
目前滴话，你建议换成那个app？
毕竟app没试用装，
你推荐一下，我去买一个试试，回来给你反馈~

**Comment by burpsuite** [comment]
最好是Surge，问题最少，其他的话比Surge稍微多一些问题，其次是一些功能，比如URL Rewrite，Shadowrocket也不是说不好，就是有我说的这个问题，其他倒还可以。

**Comment by maxming2333** [comment]
TAT，嫌贵，没得优惠

**Comment by burpsuite** [comment]
要是能找到共享的话，可以激活之后ITunes备份一下，激活数据就在备份里。也不算贵吧，合着7.5元一个人

**Comment by burpsuite** [comment]
备份之后永远都是Surge激活状态

**Comment by BurpSuite** [comment]
直接买也还可以吧，75元？大概就这样吧

**Comment by maxming2333** [comment]
我去，这都行，有没有共享的群友推荐~

**Comment by maxming2333** [comment]
Surge 现在是 300 +

**Comment by burpsuite** [comment]
你看你怎么买喽，懂我的意思吧
