### ISSUE TITLE
小火箭的skip-proxy和bypass-tun建议换成官方默认

### ISSUE THREAD

**Issue by unknowntokyo** [BurpSuite/UPlus-Shadowrocket#19]
::ffff:0:0:0:0/1, ::ffff:128:0:0:0/1在小火箭上会导致final，proxy判断有问题，你测试下你的规则和官方默认的，登陆规则外的网站，比如http://www.chinaelections.org  （只是例子），你的规则会导致链接失败，而且日志显示走的DIRECT，默认的就正常打开。cn.wsj.com一样，都是没走final，proxy，看下我写的帖子http://bbs.feng.com/forum.php?mod=viewthread&tid=10990811&page=1#pid169469947，里面还有一个workflow

**Comment by burpsuite** [comment]
好的已修复!重新导入即可!^_^ |如果还有问题欢迎反馈,如果没有请点击右下角Close Issue谢谢! |感谢反馈!

**Comment by unknowntokyo** [comment]
surge也是不需要那一段的，2.0版本之后的surge都不需要，附上之前tf的更新日志，小火箭不支持那一段的原因好像是因为不支持ipv6

**Comment by burpsuite** [comment]
好的,也已修复!
