### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by lifeva** [BurpSuite/UPlus-Shadowrocket#2]

**Comment by lifeva** [comment]
Twitter 的提醒似乎被屏蔽了，能更新时间线，但提醒无法刷新出来

**Comment by burpsuite** [comment]
谢谢,找到问题所在,请把FINAL,DIRECT 修改为Proxy即可

**Comment by burpsuite** [comment]
Settings > Config > Local Files > Config > Edit Plain Text > 最下面就能找到,把"FINAL,DIRECT"修改为"FINAL,Proxy" 然后Save,重新连接一下就行了.

**Comment by burpsuite** [comment]
稍后修复下这个问题,和Facebook

**Comment by lifeva** [comment]
umeng.com不能正常访问，必须关掉代理才行。2.5版本的config文件

**Comment by burpsuite** [comment]
友盟是广告,也是广告数据统计平台/统计平台,和CNZZ是一起的,如果"umeng"网址中包含了正常网页被拦截了请继续反馈一下网址,我重新调整一下规则哈

**Comment by burpsuite** [comment]
正常网页即:(通过"umeng"域名跳转到其他网站或网页引用了"umeng"域名的文件导致页面被拦截导致页面出错)等,如果出现这种情况请把网址发来即可

**Comment by burpsuite** [comment]
4.修正 "umeng.com"拦截问题5.更新时间:2016-6-19 21:11

**Comment by lifeva** [comment]
感谢，我试一试

**Comment by lifeva** [comment]
umeng后台可以访问了，灰常好

**Comment by burpsuite** [comment]
嗯，规则的链接也更新了，或者用ICloud导入

**Comment by burpsuite** [comment]
好的👌🏻

**Comment by burpsuite** [comment]
关闭问题就行了哈，左下角"Close and comment"
