### ISSUE TITLE
优酷6.7.4貌似已失效请确认

### ISSUE THREAD

**Issue by sagexy** [BurpSuite/UPlus-Shadowrocket#21]
优酷iPhoneV6.7.4显示网络连接异常，貌似已失效请确认

**Comment by burpsuite** [comment]
无问题

**Comment by burpsuite** [comment]
请自行检测规则是否未更新，自行检测服务器IP和打开应用的IP是否相符，如果直接通过Github下载规则导入是没用的，

**Comment by sagexy** [comment]
我尝试了下 卸载重装App 就出现网络连接异常了

**Comment by burpsuite** [comment]
1.查看请求Debugger Header，Header会包含规则下载IP以及请求接口IP和时间戳，如果两个IP一致，证明没有问题。如果不一致那么可以表明你下载规则的IP和你正在使用的服务器不符

**Comment by burpsuite** [comment]
网络异常和卸不卸载没有太大关系，基本上是接口AuthKey验证失败，AuthKey正确与错误调试参考上面。

**Comment by sagexy** [comment]
我是直接通过 https://async.be/Rule/Basic/Shadowrocket 导入的规则
![img_0132](https://user-images.githubusercontent.com/4734448/27574835-619f55d4-5b4a-11e7-8529-8c7537ed45eb.PNG)

请赐教，万分感谢！
