### ISSUE TITLE
貌似影响滴滴使用

### ISSUE THREAD

**Issue by lifeva** [BurpSuite/UPlus-Shadowrocket#3]
如题，滴滴地图走了VPN？

**Comment by burpsuite** [comment]
没走，滴滴里面用的是腾讯地图，腾讯地图也没走，滴滴应用也没走VPN，详细:http://i4.buimg.com/7178d5972c27aea1.jpg

**Comment by burpsuite** [comment]
没走VPN，滴滴里面用的是腾讯地图，滴滴应用也没走，详细: http://i4.buimg.com/7178d5972c27aea1.jpg

**Comment by burpsuite** [comment]
都是GEOIP>CN
