### ISSUE TITLE
autoupdate怎么用啊

### ISSUE THREAD

**Issue by lifeva** [BurpSuite/UPlus-Shadowrocket#4]
要在shadowrocket中设置吗？

**Comment by burpsuite** [comment]
AutoUPdate需要PHP才能运行，使用起来非常方便，主要是方便以后的更新，是更新配置文件的PHP文件，把他放在服务器上，如http://xxx.com/Shadowrocket.php 然后使用的时候只需要把这个网址放在Shadowrocket里面即可下载最新的配置文件，原理是PHP打开代码里面的那几个文件然后合并成一个Conf文件，我只需要更新代码里面的那几个文件就行了，更新这几个文件后，同步生成那4个不同格式的配置文件，也可以下载下来和那几个文件放在服务端，以后改动一个如DIRECT，其他的如Surge/Shadowrocket/A.BIG.T/Potatso也会一同修改
