### ISSUE TITLE
确实影响iPhone6的定位服务

### ISSUE THREAD

**Issue by lifeva** [BurpSuite/UPlus-Shadowrocket#5]
经常无法定位，影响滴滴、百度地图等，朋友也是这样

**Comment by burpsuite** [comment]
关键是这样的,你说是规则影响的请贴一下图,因为我没有图无法判断到底是怎么回事,你刚说完我就装了一下测试,发现所有的都是走的DIRECT，也就是直连,并没有走Proxy,所以说我现在觉得有可能是这样的,1.你有可能把设置里面的Global Routing设置成了Proxy,2.你有可能你把规则里面的GEOIP设置成了Proxy,GEOIP直接判断服务器是不是在国内,是的就走DIRECT,所以基本上百度的不可能出现走Proxy,除非设置了让他走Proxy,一共就这两个原因,你要是觉得他影响了,你可以贴出Request Log,我看一下.
![img_0217](https://cloud.githubusercontent.com/assets/14309190/16362515/4a6bcd52-3be3-11e6-963a-e7a94f7eecd8.JPG)
