### ISSUE TITLE
dns hosts能下载吗？

### ISSUE THREAD

**Issue by panpando** [BurpSuite/UPlus-Shadowrocket#6]
closed

**Comment by burpsuite** [comment]
DNS HOSTS?你指的哪个?

**Comment by burpsuite** [comment]
可以试试PandaList

**Comment by panpando** [comment]
安卓有使用pandalist这类配置的方法吗？
另外火箭里用了pandalist后appstore没法下载了

**Comment by burpsuite** [comment]
Android要是有类似应用的话我会尽快适配的

**Comment by burpsuite** [comment]
如果有AppStore问题，暂时还是无法解决的，因为要是去除AppStore规则的话，还是默认DIRECT的，暂时要是出现问题的话可以尝试把AppStore的规则改为Proxy
