### ISSUE TITLE
淘宝 图片不显示

### ISSUE THREAD

**Issue by gsgqgyq** [BurpSuite/UPlus-Shadowrocket#8]
使用这个规则的时候，淘宝客户端商品 图片不显示
还是要添加这几个规则会好一点：
DOMAIN-SUFFIX,taobaocdn.com,DIRECT
DOMAIN-SUFFIX,alicdn.com,DIRECT
DOMAIN,h5.m.taobao.com,DIRECT
DOMAIN-KEYWORD,taobao,DIRECT

**Comment by burpsuite** [comment]
已添加"DOMAIN-KEYWORD,taobao,DIRECT"
"DOMAIN-KEYWORD,taobao,DIRECT"已经包括"DOMAIN,h5.m.taobao.com,DIRECT"了故未添加.
"DOMAIN-SUFFIX,alicdn.com,DIRECT"已经存在了.
已添加"DOMAIN-SUFFIX,taobaocdn.com,DIRECT"

**Comment by burpsuite** [comment]
已修正,如果还有哪些错误的话可以继续"laaues"∩_∩,如果没有其他的问题请点击右下角的"Close and comment"∩_∩谢谢!
