### ISSUE TITLE
今日头条无法使用微信登录

### ISSUE THREAD

**Issue by GG543364** [BurpSuite/UPlus-Shadowrocket#9]
点击微信登录 许久无响应
刚才又重新弄了下配置文件 可以登录了 现在是里面的视频帖无法播放

**Comment by BurpSuite** [comment]
没有问题啊...呃...
![img_0508](https://cloud.githubusercontent.com/assets/14309190/17020814/583ba474-4f76-11e6-8157-019650ce0375.PNG)
